export interface IConfig {
  openaiApiKey: string;
  openaiOrganizationID?: string;
  openaiBasePath?: string;
  openaiModel: string;
  agentModel: string;
  legacyTriggerKeyword: string;
  privateAutoReply: boolean;
  defaultGroupMode: "quiet" | "smart" | "active" | "super_active" | "talkative";
  botDataPath: string;
  historyMessageLimit: number;
  agentRouterEnabled: boolean;
  rootAuthToken: string;
  ignoreOfficialAccounts: boolean;
  activeGroupCooldownSeconds: number;
  superActiveGroupCooldownSeconds: number;
  talkativeGroupCooldownSeconds: number;
  reminderFollowupIntervalMinutes: number;
  debugMessageTypes: boolean;
  multimodalEnabled: boolean;
  visionModel: string;
  audioModel: string;
  maxMediaBytes: number;
  videoFrameCount: number;
  replyMaxLength: number;
  replyMaxSegments: number;
  stripMarkdown: boolean;
  allowGlobalUsageReport: boolean;
  generatedFilesPath: string;
}
